import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Grid } from "@mui/material";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <Grid>
            {children}
          </Grid>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
